# Generated by Django 5.1.4 on 2024-12-04 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingsubcategory',
            name='categories',
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('photos', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings', to='categories.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Weddings',
        ),
        migrations.DeleteModel(
            name='WeddingsCategory',
        ),
        migrations.DeleteModel(
            name='WeddingSubCategory',
        ),
    ]
